### PR TITLE
Update config to use new tx & state max batch

### PR DESCRIPTION
**Pull request by karlfloersch**
**Description**
Update the config to support https://github.com/ethereum-optimism/batch-submitter/pull/65

**Additional context**
None

### CODE REVIEW

**Comment by tynes** [comment]
Is this supposed to have config file changes in it? It appears to be just a committed submodule checkout out to a commit

**Comment by karlfloersch** [comment]
Whoops yes! Force pushed & removed the config change!

**Comment by tynes** [comment]
Did you mean to include both the submodule commit and the config change?

**Comment by karlfloersch** [comment]
> Did you mean to include both the submodule commit and the config change?

Yeah the CI will fail without both changes atomically so I thought I'd test out the workflow of updating the integration repo & batch submitter together.

What is the correct next step for getting this included based on our optimism-integration PR workflow?

**Comment by tynes** [comment]
> What is the correct next step for getting this included based on our optimism-integration PR workflow?

Some PR review here:
https://github.com/ethereum-optimism/batch-submitter/pull/65#issuecomment-804502980

**Review by tynes — APPROVED** [review]

**Pull request merged**
